sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /structured_point_cloud  # This should match your publisher topic
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: /filtered_cloud  # Optional for debugging
    ns: kinect  # Update if you are using a different namespace
