# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint
    - /camera_down_joint
    - /camera_down_optical_joint
    - /camera_front_joint
    - /camera_front_optical_joint
    - bluerov2/gps_joint
    - bluerov2/imu_joint
    - bluerov2/mbe_sonar_joint
    - bluerov2/ping2_joint
    - bluerov2/ping360_sonar_joint
    - bluerov2/ping360_depth_joint
    - bluerov2/pose_sensor_default_joint
    - bluerov2/pressure_joint
    - bluerov2/thruster_0_joint
    - bluerov2/thruster_1_joint
    - bluerov2/thruster_2_joint
    - bluerov2/thruster_3_joint
    - bluerov2/thruster_4_joint
    - bluerov2/thruster_5_joint
    - bluerov2/thruster_sitl_0_joint
    - bluerov2/thruster_sitl_1_joint
    - bluerov2/thruster_sitl_2_joint
    - bluerov2/thruster_sitl_3_joint
    - bluerov2/thruster_sitl_4_joint
    - bluerov2/thruster_sitl_5_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []